import type { RawPickInput } from "./scoring/types.js";

export const gamesToday = [
  {
    id: "nyy-bos",
    awayTeam: "NYY",
    homeTeam: "BOS",
    venue: "Fenway Park",
    startTime: "7:10 PM ET",
    probablePitchers: { away: "Gerrit Cole", home: "Brayan Bello" },
    weather: { temp: 72, wind: "9 mph out to LF", impact: "Boosts right-handed pull power" },
    lineupsConfirmed: true,
    total: 8.5
  },
  {
    id: "lad-sd",
    awayTeam: "LAD",
    homeTeam: "SD",
    venue: "Petco Park",
    startTime: "8:40 PM ET",
    probablePitchers: { away: "Tyler Glasnow", home: "Dylan Cease" },
    weather: { temp: 67, wind: "6 mph in from CF", impact: "Suppresses carry" },
    lineupsConfirmed: true,
    total: 7.5
  },
  {
    id: "atl-phi",
    awayTeam: "ATL",
    homeTeam: "PHI",
    venue: "Citizens Bank Park",
    startTime: "6:45 PM ET",
    probablePitchers: { away: "Spencer Strider", home: "Zack Wheeler" },
    weather: { temp: 80, wind: "11 mph out to RF", impact: "Home-run friendly" },
    lineupsConfirmed: false,
    total: 8
  },
  {
    id: "hou-tex",
    awayTeam: "HOU",
    homeTeam: "TEX",
    venue: "Globe Life Field",
    startTime: "8:05 PM ET",
    probablePitchers: { away: "Framber Valdez", home: "Nathan Eovaldi" },
    weather: { temp: 76, wind: "Roof likely closed", impact: "Neutral run environment" },
    lineupsConfirmed: true,
    total: 8.5
  },
  {
    id: "sea-tor",
    awayTeam: "SEA",
    homeTeam: "TOR",
    venue: "Rogers Centre",
    startTime: "7:07 PM ET",
    probablePitchers: { away: "Logan Gilbert", home: "Kevin Gausman" },
    weather: { temp: 70, wind: "Roof controlled", impact: "Stable conditions" },
    lineupsConfirmed: false,
    total: 7
  }
];

export const oddsToday = [
  { gameId: "nyy-bos", market: "Moneyline", away: -132, home: +112, total: 8.5 },
  { gameId: "lad-sd", market: "Moneyline", away: -118, home: +100, total: 7.5 },
  { gameId: "atl-phi", market: "Moneyline", away: +104, home: -124, total: 8 },
  { gameId: "hou-tex", market: "Moneyline", away: -108, home: -102, total: 8.5 },
  { gameId: "sea-tor", market: "Moneyline", away: +115, home: -135, total: 7 }
];

export const rawPickInputs: RawPickInput[] = [
  {
    id: "judge-hit",
    playerId: "aaron-judge",
    market: "Batter to record a hit",
    selection: "Aaron Judge 1+ hit",
    game: "NYY @ BOS",
    gameId: "nyy-bos",
    player: "Aaron Judge",
    team: "NYY",
    odds: -210,
    baseProbability: 0.69,
    recentForm: 0.72,
    stadiumFit: 0.82,
    handednessSplit: 0.71,
    pitchTypeFit: 0.68,
    weatherBoost: 0.62,
    lineupBoost: 0.9,
    oddsValue: 0.28,
    riskPenalty: 0.16,
    reason: "Elite Fenway contact profile with strong recent hard-hit quality against sinker-heavy right-handed pitching.",
    dataPointsUsed: ["Last 15: .333 AVG", "Fenway split: +11% hit factor", "RHP split: .401 OBP", "Pitch type fit: sinker/cutter"],
    riskNotes: ["Price is expensive"]
  },
  {
    id: "betts-tb",
    playerId: "mookie-betts",
    market: "Batter 2+ total bases",
    selection: "Mookie Betts 2+ total bases",
    game: "LAD @ SD",
    gameId: "lad-sd",
    player: "Mookie Betts",
    team: "LAD",
    odds: +125,
    baseProbability: 0.48,
    recentForm: 0.78,
    stadiumFit: 0.45,
    handednessSplit: 0.76,
    pitchTypeFit: 0.73,
    weatherBoost: 0.22,
    lineupBoost: 0.84,
    oddsValue: 0.8,
    riskPenalty: 0.22,
    reason: "Positive pitch-type matchup and elite leadoff plate appearance volume offset Petco's lower carry.",
    dataPointsUsed: ["Last 10: 7 extra-base hits", "RHP split: .558 SLG", "Pitch type fit: four-seam/sweeper"],
    riskNotes: ["Pitcher strikeout ceiling is real"]
  },
  {
    id: "soto-hit",
    playerId: "juan-soto",
    market: "Batter to record a hit",
    selection: "Juan Soto 1+ hit",
    game: "NYY @ BOS",
    gameId: "nyy-bos",
    player: "Juan Soto",
    team: "NYY",
    odds: -195,
    baseProbability: 0.68,
    recentForm: 0.74,
    stadiumFit: 0.8,
    handednessSplit: 0.75,
    pitchTypeFit: 0.7,
    weatherBoost: 0.62,
    lineupBoost: 0.9,
    oddsValue: 0.35,
    riskPenalty: 0.12,
    reason: "High OBP floor, excellent left-field wall fit, and strong discipline against Bello's changeup mix.",
    dataPointsUsed: ["Last 5: 8-for-19", "Fenway history: .356 AVG", "BvP: 4-for-10", "Lineup confirmed"],
    riskNotes: []
  },
  {
    id: "cole-ks",
    market: "Pitcher strikeouts over/under",
    selection: "Gerrit Cole over 6.5 strikeouts",
    game: "NYY @ BOS",
    gameId: "nyy-bos",
    player: "Gerrit Cole",
    team: "NYY",
    odds: +102,
    baseProbability: 0.52,
    recentForm: 0.66,
    stadiumFit: 0.42,
    handednessSplit: 0.68,
    pitchTypeFit: 0.74,
    weatherBoost: 0.2,
    lineupBoost: 0.5,
    oddsValue: 0.82,
    riskPenalty: 0.28,
    reason: "Boston's projected bottom half carries above-average whiff risk versus high fastballs and sliders.",
    dataPointsUsed: ["Last 5 starts: 30.1% K rate", "Opponent K trend: 24.8%", "Pitch type fit: elevated four-seam"],
    riskNotes: ["Fenway can shorten starts if traffic rises"]
  },
  {
    id: "lad-ml",
    market: "Moneyline",
    selection: "Dodgers moneyline",
    game: "LAD @ SD",
    gameId: "lad-sd",
    team: "LAD",
    odds: -118,
    baseProbability: 0.58,
    recentForm: 0.65,
    stadiumFit: 0.5,
    handednessSplit: 0.62,
    pitchTypeFit: 0.61,
    weatherBoost: 0.2,
    lineupBoost: 0.86,
    oddsValue: 0.48,
    riskPenalty: 0.18,
    reason: "Lineup depth and bullpen availability create a small but clear model gap at current price.",
    dataPointsUsed: ["Projected lineup wRC+: 121", "Bullpen rest edge", "Implied probability below model"],
    riskNotes: ["Close divisional pricing"]
  },
  {
    id: "acuna-hit",
    playerId: "ronald-acuna",
    market: "Batter to record a hit",
    selection: "Ronald Acuna Jr. 1+ hit",
    game: "ATL @ PHI",
    gameId: "atl-phi",
    player: "Ronald Acuna Jr.",
    team: "ATL",
    odds: -175,
    baseProbability: 0.64,
    recentForm: 0.68,
    stadiumFit: 0.74,
    handednessSplit: 0.64,
    pitchTypeFit: 0.58,
    weatherBoost: 0.7,
    lineupBoost: 0.55,
    oddsValue: 0.44,
    riskPenalty: 0.22,
    reason: "Positive park and weather profile with enough contact stability to survive a difficult Wheeler matchup.",
    dataPointsUsed: ["Last 10: .310 AVG", "Citizens Bank: +8% RH hit factor", "Weather: out to RF"],
    riskNotes: ["Lineup not confirmed", "Ace opposing pitcher"]
  },
  {
    id: "strider-ks-under",
    market: "Pitcher strikeouts over/under",
    selection: "Spencer Strider under 8.5 strikeouts",
    game: "ATL @ PHI",
    gameId: "atl-phi",
    player: "Spencer Strider",
    team: "ATL",
    odds: -105,
    baseProbability: 0.55,
    recentForm: 0.46,
    stadiumFit: 0.52,
    handednessSplit: 0.5,
    pitchTypeFit: 0.56,
    weatherBoost: 0.38,
    lineupBoost: 0.48,
    oddsValue: 0.58,
    riskPenalty: 0.18,
    reason: "Number is high against a patient Phillies lineup with multiple low-chase left-handed bats.",
    dataPointsUsed: ["Opponent chase rate: bottom-third", "Line: 8.5 creates room", "Recent pitch counts stable"],
    riskNotes: ["Pitcher's raw K ceiling is elite"]
  },
  {
    id: "altuve-hit",
    playerId: "jose-altuve",
    market: "Batter to record a hit",
    selection: "Jose Altuve 1+ hit",
    game: "HOU @ TEX",
    gameId: "hou-tex",
    player: "Jose Altuve",
    team: "HOU",
    odds: -185,
    baseProbability: 0.66,
    recentForm: 0.7,
    stadiumFit: 0.6,
    handednessSplit: 0.72,
    pitchTypeFit: 0.64,
    weatherBoost: 0.3,
    lineupBoost: 0.88,
    oddsValue: 0.4,
    riskPenalty: 0.12,
    reason: "Stable contact rate and strong history versus velocity give him one of the slate's safest hit floors.",
    dataPointsUsed: ["Last 15: 18 hits", "Contact rate: 83%", "BvP: 6-for-18"],
    riskNotes: []
  },
  {
    id: "hou-tex-f5-under",
    market: "First 5 innings over/under",
    selection: "Astros/Rangers F5 under 4.5",
    game: "HOU @ TEX",
    gameId: "hou-tex",
    odds: -112,
    baseProbability: 0.57,
    recentForm: 0.58,
    stadiumFit: 0.5,
    handednessSplit: 0.56,
    pitchTypeFit: 0.62,
    weatherBoost: 0.38,
    lineupBoost: 0.5,
    oddsValue: 0.52,
    riskPenalty: 0.17,
    reason: "Both starters project above-average ground-ball or weak-contact suppression through two turns.",
    dataPointsUsed: ["Valdez GB rate: 55%", "Eovaldi home split: 3.21 ERA", "Roof neutralizes weather"],
    riskNotes: ["Two dangerous top-five offenses"]
  },
  {
    id: "vlad-hit",
    playerId: "vladimir-guerrero-jr",
    market: "Batter to record a hit",
    selection: "Vladimir Guerrero Jr. 1+ hit",
    game: "SEA @ TOR",
    gameId: "sea-tor",
    player: "Vladimir Guerrero Jr.",
    team: "TOR",
    odds: -165,
    baseProbability: 0.63,
    recentForm: 0.69,
    stadiumFit: 0.66,
    handednessSplit: 0.7,
    pitchTypeFit: 0.61,
    weatherBoost: 0.4,
    lineupBoost: 0.58,
    oddsValue: 0.47,
    riskPenalty: 0.16,
    reason: "Low strikeout profile and strong Rogers Centre history grade well against Gilbert's zone-heavy approach.",
    dataPointsUsed: ["Last 10: .342 AVG", "Home split: .392 OBP", "Pitch type fit: four-seam"],
    riskNotes: ["Lineup not confirmed"]
  },
  {
    id: "gausman-ks",
    market: "Pitcher strikeouts over/under",
    selection: "Kevin Gausman over 5.5 strikeouts",
    game: "SEA @ TOR",
    gameId: "sea-tor",
    player: "Kevin Gausman",
    team: "TOR",
    odds: -120,
    baseProbability: 0.59,
    recentForm: 0.62,
    stadiumFit: 0.55,
    handednessSplit: 0.64,
    pitchTypeFit: 0.72,
    weatherBoost: 0.35,
    lineupBoost: 0.52,
    oddsValue: 0.5,
    riskPenalty: 0.15,
    reason: "Splitter profile aligns well against Seattle's swing path and current projected lineup K rate.",
    dataPointsUsed: ["Opponent K rate: 25.1%", "Pitch type fit: splitter", "Last 5: 29 Ks"],
    riskNotes: ["Efficiency can dip with walks"]
  },
  {
    id: "nyy-ml",
    market: "Moneyline",
    selection: "Yankees moneyline",
    game: "NYY @ BOS",
    gameId: "nyy-bos",
    team: "NYY",
    odds: -132,
    baseProbability: 0.59,
    recentForm: 0.6,
    stadiumFit: 0.52,
    handednessSplit: 0.64,
    pitchTypeFit: 0.6,
    weatherBoost: 0.44,
    lineupBoost: 0.9,
    oddsValue: 0.38,
    riskPenalty: 0.16,
    reason: "Starting pitching and top-order advantage clear enough to support the road favorite price.",
    dataPointsUsed: ["Starter projection edge", "Confirmed lineup", "Bullpen leverage arms rested"],
    riskNotes: ["Rivalry volatility"]
  },
  {
    id: "full-game-over-atl",
    market: "Full game total over/under",
    selection: "Braves/Phillies over 8",
    game: "ATL @ PHI",
    gameId: "atl-phi",
    odds: +100,
    baseProbability: 0.53,
    recentForm: 0.62,
    stadiumFit: 0.76,
    handednessSplit: 0.58,
    pitchTypeFit: 0.6,
    weatherBoost: 0.78,
    lineupBoost: 0.5,
    oddsValue: 0.62,
    riskPenalty: 0.26,
    reason: "Weather and park add run support, but elite starters keep this as an aggressive-only edge.",
    dataPointsUsed: ["Wind out to RF", "Park HR factor: 112", "Both lineups top-8 ISO"],
    riskNotes: ["Two ace starters", "Lineups not confirmed"]
  },
  {
    id: "freeman-hit",
    playerId: "freddie-freeman",
    market: "Batter to record a hit",
    selection: "Freddie Freeman 1+ hit",
    game: "LAD @ SD",
    gameId: "lad-sd",
    player: "Freddie Freeman",
    team: "LAD",
    odds: -190,
    baseProbability: 0.67,
    recentForm: 0.71,
    stadiumFit: 0.5,
    handednessSplit: 0.78,
    pitchTypeFit: 0.69,
    weatherBoost: 0.22,
    lineupBoost: 0.84,
    oddsValue: 0.36,
    riskPenalty: 0.13,
    reason: "High-contact lefty bat with favorable split and low chase risk in a confirmed premium lineup slot.",
    dataPointsUsed: ["Last 15: .323 AVG", "RHP split: .396 OBP", "Contact rate: 84%"],
    riskNotes: ["Run environment is muted"]
  },
  {
    id: "seager-tb",
    playerId: "corey-seager",
    market: "Batter 2+ total bases",
    selection: "Corey Seager 2+ total bases",
    game: "HOU @ TEX",
    gameId: "hou-tex",
    player: "Corey Seager",
    team: "TEX",
    odds: +145,
    baseProbability: 0.44,
    recentForm: 0.73,
    stadiumFit: 0.62,
    handednessSplit: 0.68,
    pitchTypeFit: 0.66,
    weatherBoost: 0.32,
    lineupBoost: 0.84,
    oddsValue: 0.86,
    riskPenalty: 0.22,
    reason: "Positive plus-money edge from current barrel form and matchup against sinkers in the heart of the zone.",
    dataPointsUsed: ["Last 10: .610 SLG", "Sinker run value: +5", "Home split: .544 SLG"],
    riskNotes: ["Ground-ball pitcher can cap lift"]
  }
];

export const topTwoHitCandidates = [
  {
    player: "Juan Soto",
    team: "NYY",
    opponent: "BOS",
    opposingPitcher: "Brayan Bello",
    estimatedProbability: 0.286,
    edge: 0.052,
    confidence: "Elite",
    last5: "8-for-19",
    last10: "15-for-38",
    last15: "22-for-57",
    stadiumHistory: ".356 AVG at Fenway",
    avg: 0.318,
    obp: 0.431,
    contactRate: 0.81,
    kRate: 0.15,
    reason: "Plate discipline, Fenway spray profile, and lineup context make him the best 2-hit candidate."
  },
  {
    player: "Jose Altuve",
    team: "HOU",
    opponent: "TEX",
    opposingPitcher: "Nathan Eovaldi",
    estimatedProbability: 0.263,
    edge: 0.041,
    confidence: "Strong",
    last5: "7-for-21",
    last10: "14-for-42",
    last15: "18-for-61",
    stadiumHistory: ".304 AVG at Globe Life",
    avg: 0.301,
    obp: 0.362,
    contactRate: 0.83,
    kRate: 0.14,
    reason: "Consistent contact quality and strong velocity matchup keep his multi-hit path live."
  },
  {
    player: "Freddie Freeman",
    team: "LAD",
    opponent: "SD",
    opposingPitcher: "Dylan Cease",
    estimatedProbability: 0.249,
    edge: 0.034,
    confidence: "Strong",
    last5: "6-for-18",
    last10: "12-for-37",
    last15: "20-for-62",
    stadiumHistory: ".292 AVG at Petco",
    avg: 0.323,
    obp: 0.397,
    contactRate: 0.84,
    kRate: 0.12,
    reason: "Contact and opposite-field approach reduce risk against high-strikeout pitching."
  },
  {
    player: "Vladimir Guerrero Jr.",
    team: "TOR",
    opponent: "SEA",
    opposingPitcher: "Logan Gilbert",
    estimatedProbability: 0.236,
    edge: 0.029,
    confidence: "Playable",
    last5: "5-for-17",
    last10: "13-for-38",
    last15: "19-for-59",
    stadiumHistory: ".331 AVG at Rogers Centre",
    avg: 0.304,
    obp: 0.376,
    contactRate: 0.79,
    kRate: 0.16,
    reason: "Home environment and low K rate support the profile, but lineup status caps confidence."
  }
] as const;

export const stadiumSplits = [
  {
    id: "fenway",
    name: "Fenway Park",
    hitFactor: 1.11,
    homeRunFactor: 1.04,
    handednessNote: "Right-handed pull power and left-handed wall-ball singles both receive small boosts.",
    weatherSensitivity: "High"
  },
  {
    id: "petco",
    name: "Petco Park",
    hitFactor: 0.96,
    homeRunFactor: 0.91,
    handednessNote: "Suppresses carry, especially to center and right-center.",
    weatherSensitivity: "Medium"
  },
  {
    id: "citizens-bank",
    name: "Citizens Bank Park",
    hitFactor: 1.06,
    homeRunFactor: 1.12,
    handednessNote: "Left-handed pull power receives the largest lift.",
    weatherSensitivity: "High"
  }
];

export const modelPerformance = {
  winRate: 0.587,
  roi: 0.074,
  clv: 0.031,
  byMarket: [
    { market: "Batter to record a hit", accuracy: 0.641, roi: 0.052 },
    { market: "Pitcher strikeouts over/under", accuracy: 0.552, roi: 0.068 },
    { market: "Moneyline", accuracy: 0.573, roi: 0.028 },
    { market: "Batter 2+ total bases", accuracy: 0.421, roi: 0.091 }
  ]
};

export const settings = {
  mockMode: true,
  maxLegs: 10,
  minEdge: 0.02,
  sportsbooks: ["DraftKings", "FanDuel", "BetMGM"],
  lastModelUpdate: "2:14 PM ET"
};
